
service: auctive-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  profile: serverlessAccount
  environment:
      tableName: ${self:custom.tableName}
      tokenSecret: ${self:custom.tokenSecret}
      region: ${self:provider.region}
      cloudSearchDocEndpoint: ${self:custom.cloudSearchDocEndpoint}
      cloudSearchEndpoint: ${self:custom.cloudSearchEndpoint}
      dynamoStreamArn: ${self:custom.dynamoStreamArn}
      imageUploadBucket: ${self:custom.imageUploadBucket}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - s3:*
            - ses:*
            - cloudsearch:*
            - sns:*
          Resource: '*'
  apiGateway:
    apiKeys:
      - adminApiKey

plugins:
    - serverless-webpack
    - serverless-offline

package:
    individually: true

custom:
    # tableName: your value here
    # tokenSecret: your value here
    # cloudSearchDocEndpoint: your value here
    # cloudSearchEndpoint: your value here
    # dynamoStreamArn: your value here
    # imageUploadBucket: your value here
    tableName: auctive-table
    tokenSecret: AYWOW_AMAZING!
    cloudSearchDocEndpoint: doc-auctive-search-2hfh37w3idrm44ips6qft5mwzq.us-east-1.cloudsearch.amazonaws.com
    cloudSearchEndpoint: search-auctive-search-2hfh37w3idrm44ips6qft5mwzq.us-east-1.cloudsearch.amazonaws.com
    dynamoStreamArn: arn:aws:dynamodb:us-east-1:187673598599:table/auctive-table/stream/2021-04-02T21:32:52.441
    imageUploadBucket: auctive-auction-images
    
    webpack:
      webpackConfig: ./webpack.config.js

functions:
  test:
    handler: lambdas/endpoints/user/test.handler
    events:
      - http:
            path: test/
            method: GET
            cors: true
  createUser:
    handler: lambdas/endpoints/user/createUser.handler
    events:
      - http:
            path: users/
            method: POST
            cors: true
  login:
    handler: lambdas/endpoints/user/userLogin.handler
    events:
      - http:
            path: users/login
            method: POST
            cors: true

  change-password:
    handler: lambdas/endpoints/user/changePassword.handler
    events:
      - http:
            path: users/change-password
            method: POST
            cors: true

  getUser:
    handler: lambdas/endpoints/user/getUser.handler
    events:
        - http:
              path: users/user
              method: GET
              cors: true
        - http:
              path: users/{email}
              method: GET
              cors: true

  searchAuctions:
    handler: lambdas/endpoints/auction/getAuctions.handler
    events:
      - http:
            path: auctions/
            method: GET
            cors: true
            
  createCategory:
    handler: lambdas/endpoints/categories/createCategory.handler
    events:
      - http:
            path: categories/
            method: POST
            cors: true
            
  getScheduledActions:
    handler: lambdas/endpoints/scheduled-actions/getScheduledActions.handler
    events:
      - http:
            path: scheduled-actions/
            method: GET
            cors: true
            private: true

  sendSMS:
    handler: lambdas/endpoints/sms/sendSMS.handler
    events:
      - http:
            path: send-sms/
            method: POST
            cors: true
            private: true 
  
  imageUpload:
        handler: lambdas/endpoints/auction/imageUpload.handler
        events:
            - http:
                  path: image-upload/
                  method: POST
                  cors: true
  imagesUpload:
        handler: lambdas/endpoints/auction/imagesUpload.handler
        events:
            - http:
                  path: images-upload/
                  method: POST
                  cors: true

  stream2cloudsearch:
    handler: lambdas/streams/stream2cloudsearch.handler
    events:
      - stream: ${self:custom.dynamoStreamArn}

resources:
    Resources:
        ImageUploadBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.imageUploadBucket}
                AccessControl: PublicRead